### ISSUE TITLE
Add a select html element that listen changes

### ISSUE THREAD

**Issue by brunoprietog** [github/remote-input-element#28]
Hi,

I would like to know if it would be possible to add the html select element in addition to the input and textarea element. I would like to load content based on the changes of a selector. Would it be possible to consider this? It just means adding the possibility to consider this element.

Thanks!

**Comment by koddsson** [comment]
Hey @brunoprietog, thanks for the issue 👋🏻 

I don't think we'd like to add that functionality to `remote-input-element`. It makes assumptions that only apply to elements that can take text input and if we add `<select>` to the mix then we'd have to have a lot of branching logic to accommodate.
